#!/bin/bash
# Copyright (c) 2011 Mitchell Cooper
# don't make fun of my bash skills.

dir=`dirname "$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"`
version=`cat $dir/etc/version`
args=$@

runningq() {
    running=false
    if [ -e "$dir/etc/juno.pid" ]; then
        pid=`cat $dir/etc/juno.pid`
        running=true
    fi
}

showusage() {
    cat << EOF
usage: $0 [action]
    start       start juno IRCd
    forcestart  attempt to start juno under any circumstances
    stop        terminate juno IRCd (SIGTERM)
    rehash      rehash the server configuration file (SIGHUP)
    version     print the version of this copy of juno IRCd
    help        print this information
EOF
}

splash() {
    cat << "EOF"
      _                     _              _
     (_)                   (_)            | |
      _ _   _ _ __   ___    _ _ __ ___  __| |
     | | | | | '_ \ / _ \  | | '__/ __|/ _` |
     | | |_| | | | | (_) |-| | | | (__| (_| |
     | |\__,_|_| |_|\___/  |_|_|  \___|\__,_|
    _/ |
   |__/ 

EOF
}

check_if_running() {
    if [ ! "$running" ]; then
        echo "juno is not running!"
        exit 1
    fi
}

dostart() {
    echo "Starting juno"
    splash
    $dir/bin/juno $dir
}

start() {
    if [ "$running" ]; then
        echo "juno is already running!"
        exit 1
    fi
    dostart
}

forcestart() {
    if [ -e "$dir/etc/juno.pid" ]; then
        rm -v $dir/etc/juno.pid
    fi
    dostart
}

stop() {
    check_if_running
    echo "Signaling $pid TERM"
    kill -TERM $pid
}

main() {
    case "${args[0]}" in
        start)
            start
        ;;
        forcestart)
            forcestart
        ;;
        rehash)
            check_if_running
            echo "Signaling $pid HUP"
            kill -HUP $pid
        ;;
        stop)
            stop
        ;;
        restart)
            stop
            sleep 1
            runningq
            forcestart
        ;;
        version)
            echo juno-$version
        ;;
        help)
            showusage
        ;;
        *)
            echo "Incorrect parameter: ${args[0]}"
            echo "$0 help for help"
        ;;
    esac
}

if [ ! "$1" ]; then
    showusage
    exit
fi

runningq
main
