#!/bin/bash
# Copyright (c) 2011 Mitchell Cooper
# don't make fun of my bash skills.
cat << "EOF"
       _                     _              _
      (_)                   (_)            | |
       _ _   _ _ __   ___    _ _ __ ___  __| |
      | | | | | '_ \ / _ \  | | '__/ __|/ _` |
      | | |_| | | | | (_) |-| | | | (__| (_| |
      | |\__,_|_| |_|\___/  |_|_|  \___|\__,_|
     _/ |
    |__/ 
EOF
dir=`dirname "$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"`
echo version `cat $dir/etc/version`

if [ ! "$1" ]; then
    echo "Incorrect number of parameters."
    exit
fi

if [ -e "$dir/etc/juno.pid" ]; then
  pid=`cat $dir/etc/juno.pid`
  running=true
fi

case "$1" in
  start)
    if [ "$running" ]; then
      echo "juno is already running!"
      exit 1
    fi
    echo "Starting juno"
    $dir/bin/juno $dir
  ;;
  rehash)
    if [ ! "$running" ]; then
      echo "juno is not running!"
      exit 1
    fi
    echo "Signaling $pid HUP"
    kill -HUP $pid
  ;;
  stop)
    if [ ! "$running" ]; then
      echo "juno is not running!"
      exit 1
    fi
    echo "Signaling $pid TERM"
    kill -TERM $pid
  ;;
  restart)
    if [ ! "$running" ]; then
      echo "juno is not running!"
      exit 1
    fi
    echo "Signaling $pid TERM"
    kill -TERM $pid
    sleep 2
    echo "Starting juno"
    $dir/bin/juno $dir
  ;;
  *)
    echo "Incorrect parameter $1"
  ;;
esac
